### PR TITLE
Extract Fedora rootfs from .raw.xz

### PR DESCRIPTION
**Pull request by ericcurtin**
If target distro is Fedora, pull .raw.xz, mount the file as a loopback
device and copy the contents, preseving any symlinks, xattrs, etc. Then
cleanup after.

Signed-off-by: Eric Curtin <ecurtin@redhat.com>

### CODE REVIEW

**Comment by ericcurtin** [comment]
For the record this is untested on a Chromebook, just did  this since I had written similar stuff recently for OnePlus 6/Raspberry Pi

**Comment by ericcurtin** [comment]
I don't have a Chromebook to test yet...

**Comment by ericcurtin** [comment]
These changes get me as far as this keyblock stuff which I know very little about:

```
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-amx.ko
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-dmic.ko
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-i2s.ko
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-mixer.ko
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-mvc.ko
  INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-sfc.ko
  DEPMOD  /run/media/curtine/ROOT-A/lib/modules/5.16.0
+ cd -
+ echo Done.
Done.
+ cmd_build_vboot
+ local arch
+ local bootloader
+ local vmlinuz
+ local extra_kparams
+ echo 'Sign the kernels to boot with Chrome OS devices...'
Sign the kernels to boot with Chrome OS devices...
+ case "$ARCH" in
+ arch=arm
+ bootloader=boot_params
+ vmlinuz=kernel/kernel.itb
+ echo 'root=PARTUUID=%U/PARTNROFF=1 rootwait rw '
+ sudo vbutil_kernel --pack kernel/kernel.vboot --keyblock /usr/share/vboot/devkeys/kernel.keyblock --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --version 1 --config boot_params --bootloader boot_params --vmlinuz kernel/kernel.itb --arch arm
Unable to open file /usr/share/vboot/devkeys/kernel.keyblock
FATAL: do_vbutil_kernel: Error reading key block.
```

lead me to this helpful wiki page:

https://fedoraproject.org/wiki/Architectures/ARM/Chromebook#From_within_ChromeOS

Sounds like from this point, it's better if you have a real Chromebook.

**Comment by eballetbo** [comment]
> These changes get me as far as this keyblock stuff which I know very little about:
> 
> ```
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-amx.ko
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-dmic.ko
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-i2s.ko
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-mixer.ko
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-mvc.ko
>   INSTALL /run/media/curtine/ROOT-A/lib/modules/5.16.0/kernel/sound/soc/tegra/snd-soc-tegra210-sfc.ko
>   DEPMOD  /run/media/curtine/ROOT-A/lib/modules/5.16.0
> + cd -
> + echo Done.
> Done.
> + cmd_build_vboot
> + local arch
> + local bootloader
> + local vmlinuz
> + local extra_kparams
> + echo 'Sign the kernels to boot with Chrome OS devices...'
> Sign the kernels to boot with Chrome OS devices...
> + case "$ARCH" in
> + arch=arm
> + bootloader=boot_params
> + vmlinuz=kernel/kernel.itb
> + echo 'root=PARTUUID=%U/PARTNROFF=1 rootwait rw '
> + sudo vbutil_kernel --pack kernel/kernel.vboot --keyblock /usr/share/vboot/devkeys/kernel.keyblock --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --version 1 --config boot_params --bootloader boot_params --vmlinuz kernel/kernel.itb --arch arm
> Unable to open file /usr/share/vboot/devkeys/kernel.keyblock
> FATAL: do_vbutil_kernel: Error reading key block.
> ```
> 
> lead me to this helpful wiki page:
> 
> https://fedoraproject.org/wiki/Architectures/ARM/Chromebook#From_within_ChromeOS
> 
> Sounds like from this point, it's better if you have a real Chromebook.

Debian has a package with the devkeys packed that you can install it ( vboot-kernel-utils ), that's not the case for Fedora. It would be nice also have a similar package for Fedora, but meanwhile, as a workaround you need to copy manually the keys in order to sign properly the chromebook kernels.

**Comment by eballetbo** [comment]
This needs more work as copying directly the contents of the Fedora raw image doesn't work, i.e you need at least to modify the /etc/fstab file to mount properly the rootfs.

**Comment by ericcurtin** [comment]
rebased

**Comment by eballetbo** [comment]
For anyone interested on add support for Fedora, please take a look at the PR from @dorindabassey

* https://github.com/eballetbo/chromebooks/pull/16

I'm going to close this PR and continue the discussions there. Thanks!

**Pull request closed without merging**
